package refDemo.PursuerEvader;


import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class vehicle extends  ViewableDigraph{

public vehicle(){
this("vehicle",new vect2DEnt(40,40));
}

public vehicle (String nm, vect2DEnt initialPos ){
super(nm);

addInport("in");
addOutport("out");
addOutport("outDraw");

ViewableAtomic drv = new driver(nm +".drv");
drv.setLayoutName("name + \".drv\"");
ViewableAtomic nic = new wirelessNIC("WI-FI");
ViewableDigraph vd  = new  vehicleDyn("vd "+nm,initialPos);
vd.setLayoutName("\"vd \" + name");


add(drv);
add(vd);
add(nic);


addCoupling(drv,"brake",vd,"brake");
addCoupling(drv, "maxSpeed", vd, "desiredSpeed");
addCoupling(drv, "maxAccel", vd, "desiredAccel");
addCoupling(drv,"accelerate",vd,"accelerate");
addCoupling(vd,"position",drv,"position");

addCoupling(vd,"position",nic,"inBroadcast");
addCoupling(nic,"outBroadcast",this,"out");
addCoupling(vd,"outDraw",this,"outDraw");
addCoupling(this,"in",nic,"inRecv");
addCoupling(nic,"outRecv",drv,"desiredPosition");


}



    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(872, 313);
        ((ViewableComponent)withName("WI-FI")).setPreferredLocation(new Point(-30, 78));
        ((ViewableComponent)withName(name + ".drv")).setPreferredLocation(new Point(-29, 221));
        ((ViewableComponent)withName("vd " + name)).setPreferredLocation(new Point(233, 8));
    }
}



