package refDemo.DigAudio;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;


public class coord_test extends ViewableDigraph
{
  public coord_test()
  {
    this("Coordinator Test");
  }

  public coord_test(String name)
  {
    super(name);

    DAP c = new DAP("DAP");
    coord_gen gc = new coord_gen("Generator");

    add(c);
    add(gc);

    addCoupling(gc, "ostart", c, "start");
    addCoupling(gc, "oload", c, "load");
    addCoupling(gc, "filter_type", c, "filter_type");
    addCoupling(gc, "window_type", c, "window_type");
    addCoupling(gc, "fc1", c, "fc1");
    addCoupling(gc, "fc1_1", c, "fc1_1");
    addCoupling(gc, "fc1_2", c, "fc1_2");
    addCoupling(gc, "fc2", c, "fc2");
    addCoupling(gc, "fc2_1", c, "fc2_1");
    addCoupling(gc, "fc2_2", c, "fc2_2");
    addCoupling(gc, "fs", c, "fs");

    addCoupling(c, "out", gc, "in");

    /*Coordinator c = new Coordinator("Coordinator");
    coord_gen gc = new coord_gen("Generator");

    add(c);
    add(gc);

    addCoupling(gc, "ostart", c, "start");
    addCoupling(gc, "oload", c, "load");
    addCoupling(gc, "filter_type", c, "filter_type");
    addCoupling(gc, "window_type", c, "window_type");
    addCoupling(gc, "fc1", c, "fc1");
    addCoupling(gc, "fc1_1", c, "fc1_1");
    addCoupling(gc, "fc1_2", c, "fc1_2");
    addCoupling(gc, "fc2", c, "fc2");
    addCoupling(gc, "fc2_1", c, "fc2_1");
    addCoupling(gc, "fc2_2", c, "fc2_2");
    addCoupling(gc, "fs", c, "fs");

    addCoupling(c, "out", gc, "in");*/
  }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(925, 566);
        ((ViewableComponent)withName("Generator")).setPreferredLocation(new Point(-10, 12));
        ((ViewableComponent)withName("DAP")).setPreferredLocation(new Point(167, 0));
    }
}
