package refDemo.DigAudio;

import java.awt.Dimension;
import java.awt.Point;

import model.plots.CellGridPlot;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class Coord_Plot extends ViewableDigraph
{
  protected CellGridPlot timeP;

  public Coord_Plot()
  {
    this("Coordinator Plot");
  }
  public Coord_Plot(String name)
  {
    super(name);
    Coordinator comp = new Coordinator("Coordinator");
    timeP = new CellGridPlot("Time Plot",200,0.4);
    //timeP = new CellGridPlot("Time Plot", 1, 300, 300);
    timeP.setCellGridViewLocation(100,300);
    timeP.setSpaceSize(200,200);
    timeP.setCellSize(3);
    timeP.setTimeScale(186);
    timeP.setHidden(false);


    addOutport("out");
    addOutport("load");



    add(comp);
    add(timeP);

    addCoupling(comp, "out", this, "out");
    addCoupling(comp, "load", this, "load");

    //addCoupling(comp,"out",timeP,"timePlot");
    addCoupling(comp,"out",timeP,"pulsePlot");
  }


    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(417, 232);
        ((ViewableComponent)withName("Coordinator")).setPreferredLocation(new Point(-12, 43));
        ((ViewableComponent)withName("Time Plot")).setPreferredLocation(new Point(160, 31));
    }
}
