package refDemo.DigAudio;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;


public class FBflyMod extends ViewableDigraph
{
  public FBflyMod()
  {
    this("FFT Butterfly Module");
  }
  public FBflyMod(String name)
  {
    super(name);

    addInport("N");
    addInport("start");
    addInport("k");
    addInport("rd1");
    addInport("rd2");
    addInport("wr1");
    addInport("wr2");
    addInport("dataR");
    addInport("dataI");

    addOutport("odataR");
    addOutport("odataI");
    addOutport("done");

    Memory mem1x1_1 = new Memory("Memory 1x1 1", 2);
    Memory mem1x1_2 = new Memory("Memory 1x1 2", 2);
    FFTButterfly bfly = new FFTButterfly("FFT Butterfly");

    add(mem1x1_1);
    add(mem1x1_2);
    add(bfly);

    addCoupling(this, "N", bfly, "N");
    addCoupling(this, "start", bfly, "start");
    addCoupling(this, "k", bfly, "k");
    addCoupling(this, "rd1", mem1x1_1, "rd");
    addCoupling(this, "rd2", mem1x1_2, "rd");
    addCoupling(this, "wr1", mem1x1_1, "wr");
    addCoupling(this, "wr2", mem1x1_2, "wr");
    addCoupling(this, "dataR", mem1x1_1, "dataR");
    addCoupling(this, "dataI", mem1x1_1, "dataI");
    addCoupling(this, "dataR", mem1x1_2, "dataR");
    addCoupling(this, "dataI", mem1x1_2, "dataI");

    addCoupling(mem1x1_1, "odataR", bfly, "aR");
    addCoupling(mem1x1_1, "odataI", bfly, "aI");
    addCoupling(mem1x1_2, "odataR", bfly, "bR");
    addCoupling(mem1x1_2, "odataI", bfly, "bI");

    addCoupling(bfly, "done", mem1x1_1, "wr");
    addCoupling(bfly, "done", mem1x1_2, "wr");
    addCoupling(bfly, "AR", mem1x1_1, "dataR");
    addCoupling(bfly, "AI", mem1x1_1, "dataI");
    addCoupling(bfly, "BR", mem1x1_2, "dataR");
    addCoupling(bfly, "BI", mem1x1_2, "dataI");
    addCoupling(bfly, "done", this, "done");

    addCoupling(mem1x1_1, "odataR", this, "odataR");
    addCoupling(mem1x1_1, "odataI", this, "odataI");
    addCoupling(mem1x1_2, "odataR", this, "odataR");
    addCoupling(mem1x1_2, "odataI", this, "odataI");

  }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(473, 448);
        ((ViewableComponent)withName("FFT Butterfly")).setPreferredLocation(new Point(89, 156));
        ((ViewableComponent)withName("Memory 1x1 2")).setPreferredLocation(new Point(77, 298));
        ((ViewableComponent)withName("Memory 1x1 1")).setPreferredLocation(new Point(80, 43));
    }
}
