package refDemo.DigAudio;

import java.awt.Dimension;
import java.awt.Point;

import model.plots.CellGridPlot;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;


public class inputTestMod extends ViewableDigraph
{
  public inputTestMod()
  {
    this("Input Test Module");
  }

  public inputTestMod(String name)
  {
    super(name);

    addInport("start");
    addOutport("o_xR");
    addOutport("o_xI");
    addOutport("rd");
    addOutport("row");

    inputUnitTest t = new inputUnitTest("Input Generator");
    inputUnit i = new inputUnit("Input Unit");
    CellGridPlot timeP = new CellGridPlot("Time Plot",200,2);


    timeP.setCellGridViewLocation(100,300);
    timeP.setSpaceSize(200,200);
    timeP.setCellSize(3);
    timeP.setTimeScale(186);

    add(t);
    add(i);
    add(timeP);

    addCoupling(t, "data", i, "data");
    addCoupling(t, "M", i, "M");

    addCoupling(i, "oxR", this, "o_xR");
    addCoupling(i, "oxI", this, "o_xI");
    addCoupling(i, "rd", this, "rd");
    addCoupling(i, "row", this, "row");

    addCoupling(this, "start", t, "start");
    addCoupling(t, "data", timeP, "pulsePlot");
  }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(284, 152);
        ((ViewableComponent)withName("Input Generator")).setPreferredLocation(new Point(-8, 17));
        ((ViewableComponent)withName("Input Unit")).setPreferredLocation(new Point(-10, 73));
    }
}
