/*      Copyright 2002 Arizona Board of regents on behalf of
 *                  The University of Arizona
 *                     All Rights Reserved
 *         (USE & RESTRICTION - Please read COPYRIGHT file)
 *
 *  Version    : DEVSJAVA 2.7
 *  Date       : 08-15-02
 */


package refDemo.RoadTraffic;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;


public class AccidentEf extends ViewableDigraph{


public AccidentEf(){
    super("AccidentEf");
    efConstruct(1,20,0.66);//1, updating time; 20, time of accident occurs;
  }                        //0.66 accident level

public AccidentEf(String nm,double int_arr_t, double normal_time,double level){
    super(nm);
    efConstruct(int_arr_t, normal_time,level);
}

public void efConstruct(double int_arr_t, double normal_time,double level){

    addInport("in");
    addOutport("out");
    addOutport("queue");

    controlerEf contrEf = new controlerEf("cEf",int_arr_t, normal_time,level);
    roadCellSpace rSpace = new roadCellSpace(20,1); //20, xcoord, 1: ycoord
    numberInfirstcell count=new numberInfirstcell("number of 1st cell");

     add(contrEf);
     add(rSpace);
     add(count);

     initialize();

   addCoupling(contrEf,"carout",rSpace,"start");
   addCoupling(count,"queue",this,"queue");
   addCoupling(contrEf,"accident",rSpace,"accident");
   addCoupling(rSpace,"queue",count,"in");

}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(520, 381);
        ((ViewableComponent)withName("number of 1st cell")).setPreferredLocation(new Point(130, 313));
        ((ViewableComponent)withName("Road Cell Space")).setPreferredLocation(new Point(231, 45));
        ((ViewableComponent)withName("cEf")).setPreferredLocation(new Point(1, 101));
    }
}
