/*      Copyright 2002 Arizona Board of regents on behalf of
 *                  The University of Arizona
 *                     All Rights Reserved
 *         (USE & RESTRICTION - Please read COPYRIGHT file)
 *
 *  Version    : DEVSJAVA 2.7
 *  Date       : 08-15-02
 */


package refDemo.RoadTraffic;

import java.awt.Dimension;

import GenCol.entity;
import view.modeling.ViewableDigraph;


public class controlerEf extends ViewableDigraph{


public controlerEf(){
    super("controlerEf");
    efConstruct(1,20,1);
}
//int_arr_t: the interval time of updating for each cell
//normal_time, the time until accident happen
//level: accidentlevel
public controlerEf(String nm,double int_arr_t,double normal_time,double level){
    super(nm);
    efConstruct(int_arr_t,normal_time,level);
}

public void efConstruct(double int_arr_t,double normal_time,double level){

    addInport("start constant");
    addInport("start random");
    addInport("accidentlevel");
    addOutport("carout");
    addOutport("accident");

    carGenr carGen = new carGenr("carGen",int_arr_t);
    accidentControler accidentCon = new accidentControler("accidentCon",normal_time,level);

     add(carGen);
     add(accidentCon);
     carGen.setHidden(true);
     accidentCon.setHidden(true);

     addTestInput("start constant",new entity());
     addTestInput("start random",new entity());
     initialize();

     addCoupling(this,"start constant",carGen,"constant");
     addCoupling(this,"start random",carGen,"random");
     addCoupling(this,"accidentlevel",accidentCon,"accidentlevel");
     addCoupling(this,"stop",carGen,"stop");
     addCoupling(carGen,"carout",this,"carout");
     addCoupling(accidentCon,"out",this,"accident");

}


    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(223, 169);
    }
}
