/*      Copyright 2002 Arizona Board of regents on behalf of
 *                  The University of Arizona
 *                     All Rights Reserved
 *         (USE & RESTRICTION - Please read COPYRIGHT file)
 *
 *  Version    : DEVSJAVA 2.7
 *  Date       : 08-15-02
 */


package refDemo.RoadTraffic;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;


public class lightControlEf extends ViewableDigraph{


public lightControlEf(){
    super("lightControlEf");
    efConstruct(1,20,0);
}

public lightControlEf(String nm,double int_arr_t, double normal_time,double level){
    super(nm);
    efConstruct(int_arr_t, normal_time,level);
}

public void efConstruct(double int_arr_t, double normal_time,double level){

    addInport("in");
    addOutport("out");
    addOutport("queue");

    controlerEf contrEf = new controlerEf("cEf",int_arr_t, normal_time,level);
    roadCellSpace rSpace = new roadCellSpace(10,10);
    turnOnlight power=new turnOnlight("power control",10);

     add(contrEf);
     add(rSpace);
     add(power);

     initialize();

   addCoupling(contrEf,"carout",rSpace,"start");
   addCoupling(rSpace,"queue",this,"queue");
   addCoupling(power,"turn on light",rSpace,"lightcontrol");
   addCoupling(contrEf,"accident",rSpace,"accident");

}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(687, 471);
        ((ViewableComponent)withName("power control")).setPreferredLocation(new Point(8, 303));
        ((ViewableComponent)withName("cEf")).setPreferredLocation(new Point(20, 89));
        ((ViewableComponent)withName("Road Cell Space")).setPreferredLocation(new Point(285, 50));
    }
}
