package refDemo.Grating;
import java.awt.Dimension;
import java.awt.Point;

import model.plots.CellGridPlot;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;


public class couple1 extends ViewableDigraph{

public couple1 (){
super("couple1 ");

addInport("velocity1");
addOutport("outT1");

double initialPosition = 0;
double quantum = 0.1, eps = 0;

ViewableAtomic comp = new oneDCompIntMod("oneDCompIntMod",quantum,initialPosition,0,0);
add(comp);

ViewableAtomic time1 = new timeobs("timeobs");
add(time1);

addCoupling(time1,"tout",this,"outT1");


addCoupling(this,"velocity1",comp,"velocity");
ViewableAtomic speed1 = new speedobs1("speedobs1",10);
add(speed1);
addCoupling(comp,"out",speed1,"pin");
addCoupling(speed1,"vout",time1,"V1");
addCoupling(comp,"outV",speed1,"vin");
ViewableAtomic decelerator1 = new decelerator1("decelerator1",5,-.1,-3,-3,-3,-1,-1,-2);
add(decelerator1);

addCoupling(decelerator1,"out",comp,"in");
addCoupling(comp,"out",decelerator1,"in");

//addCoupling(comp,"out",this,"outP");
//addCoupling(comp,"outV",this,"outV");

CellGridPlot timeP = new CellGridPlot("Time Plot",20,220);
timeP.setCellGridViewLocation(500,500);
timeP.setSpaceSize(100,40);
timeP.setCellSize(5);
timeP.setTimeScale(20);

add(timeP);
addCoupling(comp,"out",timeP,"timePlot");
addCoupling(comp,"outV",timeP,"timePlot");
}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(681, 282);
        ((ViewableComponent)withName("oneDCompIntMod")).setPreferredLocation(new Point(145, 81));
        ((ViewableComponent)withName("decelerator1")).setPreferredLocation(new Point(149, 223));
        ((ViewableComponent)withName("timeobs")).setPreferredLocation(new Point(364, 63));
        ((ViewableComponent)withName("speedobs1")).setPreferredLocation(new Point(327, 181));
    }
}
