/*      Copyright 2002 Arizona Board of regents on behalf of
 *                  The University of Arizona
 *                     All Rights Reserved
 *         (USE & RESTRICTION - Please read COPYRIGHT file)
 *
 *  Version    : DEVSJAVA 2.7
 *  Date       : 08-15-02
 */

package refDemo.Simpnet;

import java.awt.Dimension;
import java.awt.Point;

import GenCol.entity;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class coupledStations extends ViewableDigraph{

public coupledStations(){
    super("coupledStations");
    int window = 4, totalvolume = 1200, packetsize = 100,transdelay=1;

    ViewableAtomic s1 = new stationnew("station1",window,totalvolume,packetsize,"station2",transdelay);
    ViewableAtomic s2 = new stationnew("station2",window,totalvolume,packetsize,"station2",transdelay);

     add(s1);
     add(s2);

    addInport("start");
    addTestInput("start",new entity());

    addCoupling(this,"start",s1,"start");
    addCoupling(s1,"out",s2,"in");
    addCoupling(s2,"out",s1,"in");
}


    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(549, 476);
        ((ViewableComponent)withName("station1")).setPreferredLocation(new Point(90, 55));
        ((ViewableComponent)withName("station2")).setPreferredLocation(new Point(81, 179));
    }
}
