/*      Copyright 2002 Arizona Board of regents on behalf of
 *                  The University of Arizona
 *                     All Rights Reserved
 *         (USE & RESTRICTION - Please read COPYRIGHT file)
 *
 *  Version    : DEVSJAVA 2.7
 *  Date       : 08-15-02
 */


package refDemo.Simpnet;

import java.awt.Dimension;
import java.awt.Point;

import GenCol.entity;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class network extends ViewableDigraph{

public network(){
    super("network");
    int window = 4, totalvolume = 1200, packetsize = 100,transdelay = 1, bridgedelay = 1;

    ViewableAtomic t = new TObs("TObs");

    ViewableAtomic s1 = new stationnew("station1",window,totalvolume,packetsize,"station2",transdelay);
    ViewableAtomic s2 = new stationnew("station2",window,totalvolume,packetsize,"station1",transdelay);
    ViewableAtomic s3 = new stationnew("station3",window,totalvolume,packetsize,"station1",transdelay);

    ViewableAtomic b1 = new bridge("bridge1","LANAin","Bridge2in","LANAout","Bridge2out","station2",bridgedelay);
    ViewableAtomic b2 = new bridge("bridge2","LANCin","Bridge1in","LANCout","Bridge1out","station2",bridgedelay);
    ViewableAtomic b3 = new bridge("bridge3","LANAin","LANDin","LANAout","LANDout","station3",bridgedelay);

     add(t);
     add(s1);
     add(s2);
     add(s3);
     add(b1);
     add(b2);
     add(b3);

    addInport("start");
    addOutport("tout");
    addTestInput("start",new entity());

    addCoupling(this,"start",s1,"start");
    addCoupling(this,"start",t,"start");

    addCoupling(s1,"done",t,"done");
    addCoupling(t,"tout",this,"tout");
    addCoupling(s1,"out",b1,"LANAin");
    addCoupling(b1,"LANAout",s1,"in");
    addCoupling(b1,"Bridge2out",b2,"Bridge1in");
    addCoupling(b2,"Bridge1out",b1,"Bridge2in");
    addCoupling(s2,"out",b2,"LANCin");
    addCoupling(b2,"LANCout",s2,"in");

    addCoupling(s1,"out",b3,"LANAin");
    addCoupling(b3,"LANAout",s1,"in");
    addCoupling(s3,"out",b3,"LANDin");
    addCoupling(b3,"LANDout",s3,"in");
}


    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(982, 476);
        ((ViewableComponent)withName("bridge3")).setPreferredLocation(new Point(359, 193));
        ((ViewableComponent)withName("station1")).setPreferredLocation(new Point(156, 93));
        ((ViewableComponent)withName("bridge2")).setPreferredLocation(new Point(83, 256));
        ((ViewableComponent)withName("bridge1")).setPreferredLocation(new Point(88, 182));
        ((ViewableComponent)withName("station3")).setPreferredLocation(new Point(367, 269));
        ((ViewableComponent)withName("TObs")).setPreferredLocation(new Point(153, 4));
        ((ViewableComponent)withName("station2")).setPreferredLocation(new Point(148, 362));
    }
}
