/*      Copyright 2002 Arizona Board of regents on behalf of
 *                  The University of Arizona
 *                     All Rights Reserved
 *         (USE & RESTRICTION - Please read COPYRIGHT file)
 *
 *  Version    : DEVSJAVA 2.7
 *  Date       : 08-15-02
 */


package refDemo.Simpnet;

import java.awt.Dimension;
import java.awt.Point;

import GenCol.entity;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class OneBridge extends ViewableDigraph{

public OneBridge(){
    super("OneBridge");
    int window = 4, totalvolume = 1200, packetsize = 100,transdelay=1, bridgedelay=1;

    ViewableAtomic t = new TObs("TObs");
    ViewableAtomic s1 = new stationnew("station1",window,totalvolume,packetsize,"station2",transdelay);
    ViewableAtomic s2 = new stationnew("station2",window,totalvolume,packetsize,"station2",transdelay);
    ViewableAtomic b1 = new bridge("bridge1","LANAin","LANBin","LANAout","LANBout","station2",1);

     add(t);
     add(s1);
     add(s2);
     add(b1);

    addInport("start");
    addOutport("tout");
    addTestInput("start",new entity());

    addCoupling(this,"start",s1,"start");
    addCoupling(this,"start",t,"start");
    addCoupling(t,"tout",this,"tout");

    addCoupling(s1,"done",t,"done");
    addCoupling(s1,"out",b1,"LANAin");
    addCoupling(b1,"LANAout",s1,"in");
    addCoupling(b1,"LANBout",s2,"in");
    addCoupling(s2,"out",b1,"LANBin");
}


    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(549, 476);
        ((ViewableComponent)withName("bridge1")).setPreferredLocation(new Point(53, 214));
        ((ViewableComponent)withName("TObs")).setPreferredLocation(new Point(63, 41));
        ((ViewableComponent)withName("station1")).setPreferredLocation(new Point(66, 123));
        ((ViewableComponent)withName("station2")).setPreferredLocation(new Point(68, 290));
    }
}
