/*      Copyright 2002 Arizona Board of regents on behalf of
 *                  The University of Arizona
 *                     All Rights Reserved
 *         (USE & RESTRICTION - Please read COPYRIGHT file)
 *
 *  Version    : DEVSJAVA 2.7
 *  Date       : 08-15-02
 */


package refDemo.Simpnet;

import java.awt.Dimension;
import java.awt.Point;

import GenCol.entity;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class TwoBridges extends ViewableDigraph{

public TwoBridges(){
    super("TwoBridges");
    int window = 4, totalvolume = 1200, packetsize = 100,transdelay=1, bridgedelay=1;

    ViewableAtomic t = new TObs("TObs");
    ViewableAtomic s1 = new stationnew("station1",window,totalvolume,packetsize,"station2",transdelay);
    ViewableAtomic s2 = new stationnew("station2",window,totalvolume,packetsize,"station2",transdelay);
    ViewableAtomic b1 = new bridge("bridge1","LANAin","Bridge2in","LANAout","Bridge2out","station2",bridgedelay);
    ViewableAtomic b2 = new bridge("bridge2","LANCin","Bridge1in","LANCout","Bridge1out","station2",bridgedelay);

     add(t);
     add(s1);
     add(s2);
     add(b1);
     add(b2);

    addInport("start");
    addOutport("tout");
    addTestInput("start",new entity());

    addCoupling(this,"start",s1,"start");
    addCoupling(this,"start",t,"start");

    addCoupling(s1,"done",t,"done");
    addCoupling(t,"tout",this,"tout");
    addCoupling(s1,"out",b1,"LANAin");
    addCoupling(b1,"LANAout",s1,"in");
    addCoupling(b1,"Bridge2out",b2,"Bridge1in");
    addCoupling(b2,"Bridge1out",b1,"Bridge2in");
    addCoupling(s2,"out",b2,"LANCin");
    addCoupling(b2,"LANCout",s2,"in");
}


    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(549, 476);
        ((ViewableComponent)withName("bridge2")).setPreferredLocation(new Point(139, 275));
        ((ViewableComponent)withName("station1")).setPreferredLocation(new Point(179, 98));
        ((ViewableComponent)withName("bridge1")).setPreferredLocation(new Point(135, 191));
        ((ViewableComponent)withName("station2")).setPreferredLocation(new Point(148, 362));
        ((ViewableComponent)withName("TObs")).setPreferredLocation(new Point(178, 11));
    }
}
