package refDemo.RobotFormation;

import java.awt.Dimension;
import java.awt.Point;

import model.plots.CellGridPlot;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class display extends ViewableDigraph {

	public display() {
		super("display");

		addInport("p1in");
		addInport("p2in");
		addInport("p3in");
		addInport("p4in");
		addInport("p5in");
		addInport("p6in");
		addInport("startx");
		addInport("starty");
		addInport("endx");
		addInport("endy");

		ViewableAtomic proc = new displaydataproc("DataProc");
		CellGridPlot t = new CellGridPlot("Moving Plot", 0, 1200, 1200);
		t.setCellGridViewLocation(600, 300);

		add(proc);
		add(t);

		addCoupling(this, "p1in", proc, "p1in");
		addCoupling(this, "p2in", proc, "p2in");
		addCoupling(this, "p3in", proc, "p3in");
		addCoupling(this, "p4in", proc, "p4in");
		addCoupling(this, "p5in", proc, "p5in");
		addCoupling(this, "p6in", proc, "p6in");
		addCoupling(this, "startx", proc, "o1");
		addCoupling(this, "starty", proc, "o2");
		addCoupling(this, "endx", proc, "o3");
		addCoupling(this, "endy", proc, "o4");
		addCoupling(proc, "out", t, "drawCellToScale");

		initialize();
		preferredSize = new Dimension(100, 50);
		proc.setPreferredLocation(new Point(13, 18));

	}

	/**
	 * Automatically generated by the SimView program. Do not edit this manually, as
	 * such changes will get overwritten.
	 */
	public void layoutForSimView() {
		preferredSize = new Dimension(248, 234);
		((ViewableComponent) withName("DataProc")).setPreferredLocation(new Point(22, 213));
	}
}
