package refDemo.RobotFormation;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class Ef2 extends ViewableDigraph {

	public Ef2() {
		super("Ef");

		addOutport("command");
		addOutport("L");
		addOutport("T");
		addOutport("velocity");
		addOutport("stop");
		addOutport("command");

		ViewableAtomic g = new generator("Generator", 100, "./src/StudentProjects/FreeSpaceInput.txt");

		add(g);

		addCoupling(g, "L", this, "L");
		addCoupling(g, "T", this, "T");
		addCoupling(g, "stop", this, "stop");
		addCoupling(g, "command", this, "command");
		addCoupling(g, "velocity", this, "velocity");

		preferredSize = new Dimension(100, 50);
		g.setPreferredLocation(new Point(150, 150));
	}

	/**
	 * Automatically generated by the SimView program. Do not edit this manually, as
	 * such changes will get overwritten.
	 */
	public void layoutForSimView() {
		preferredSize = new Dimension(348, 144);
		((ViewableComponent) withName("Generator")).setPreferredLocation(new Point(30, 15));
	}
}
