package refDemo.RobotFormation;

import java.awt.Dimension;
import java.awt.Point;

import refDemo.PursuerEvader.vect2DEnt;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class Environment extends ViewableDigraph {

	public Environment() {
		super("Environment");

		addInport("pin");
		addInport("vin");
		addOutport("startx");
		addOutport("starty");
		addOutport("endx");
		addOutport("endy");

		ViewableAtomic o1 = new obstacle("obstacle1", new vect2DEnt(-200, 300), new vect2DEnt(-200, 200),
				new vect2DEnt(200, 300), new vect2DEnt(200, 200));
		ViewableAtomic o2 = new obstacle("obstacle2", new vect2DEnt(-200, 200), new vect2DEnt(-200, -100),
				new vect2DEnt(200, 200), new vect2DEnt(200, -100));
		ViewableAtomic o3 = new obstacle("obstacle3", new vect2DEnt(-200, -100), new vect2DEnt(-200, -300),
				new vect2DEnt(200, -100), new vect2DEnt(200, -300));

		add(o1);
		add(o2);
		add(o3);

		addCoupling(this, "pin", o1, "pin");
		addCoupling(this, "vin", o1, "vin");
		addCoupling(this, "pin", o2, "pin");
		addCoupling(this, "vin", o2, "vin");
		addCoupling(this, "pin", o3, "pin");
		addCoupling(this, "vin", o3, "vin");
		addCoupling(o1, "startx", this, "startx");
		addCoupling(o1, "starty", this, "starty");
		addCoupling(o1, "endx", this, "endx");
		addCoupling(o1, "endy", this, "endy");
		addCoupling(o2, "startx", this, "startx");
		addCoupling(o2, "starty", this, "starty");
		addCoupling(o2, "endx", this, "endx");
		addCoupling(o2, "endy", this, "endy");
		addCoupling(o3, "startx", this, "startx");
		addCoupling(o3, "starty", this, "starty");
		addCoupling(o3, "endx", this, "endx");
		addCoupling(o3, "endy", this, "endy");

		preferredSize = new Dimension(549, 181);
		o1.setPreferredLocation(new Point(239, 23));
		o2.setPreferredLocation(new Point(239, 23));
		o3.setPreferredLocation(new Point(239, 23));

	}

	/**
	 * Automatically generated by the SimView program. Do not edit this manually, as
	 * such changes will get overwritten.
	 */
	public void layoutForSimView() {
		preferredSize = new Dimension(272, 291);
		((ViewableComponent) withName("obstacle2")).setPreferredLocation(new Point(-12, 104));
		((ViewableComponent) withName("obstacle1")).setPreferredLocation(new Point(-10, 18));
		((ViewableComponent) withName("obstacle3")).setPreferredLocation(new Point(-13, 191));
	}
}
