package refDemo.RobotFormation;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class Robots extends ViewableDigraph {

	public Robots() {
		super("Robots");

		addInport("vin");
		addInport("L");
		addInport("T");
		addInport("stop");
		addInport("startx");
		addInport("starty");
		addInport("endx");
		addInport("endy");
		addInport("formation");
		addOutport("pout1");
		addOutport("pout2");
		addOutport("pout3");
		addOutport("pout4");
		addOutport("pout5");
		addOutport("pout6");

		ViewableDigraph r1 = new r1();
		ViewableDigraph f = new followers();

		add(r1);
		add(f);

		addCoupling(this, "vin", r1, "vin");
		addCoupling(this, "stop", r1, "stop");
		addCoupling(this, "L", r1, "L");
		addCoupling(this, "T", r1, "T");
		addCoupling(this, "formation", r1, "formation");
		addCoupling(this, "startx", r1, "startx");
		addCoupling(this, "starty", r1, "starty");
		addCoupling(this, "endx", f, "endx");
		addCoupling(this, "endy", f, "endy");
		addCoupling(this, "L", f, "L");
		addCoupling(this, "T", f, "T");
		addCoupling(this, "formation", f, "formation");
		addCoupling(this, "stop", f, "stop");

		addCoupling(r1, "pout", f, "pin");
		addCoupling(r1, "command", f, "formation");
		addCoupling(r1, "vout", f, "vin");
		addCoupling(f, "command", r1, "formation");

		addCoupling(r1, "pout", this, "pout1");
		addCoupling(f, "p2out", this, "pout2");
		addCoupling(f, "p3out", this, "pout3");
		addCoupling(f, "p4out", this, "pout4");
		addCoupling(f, "p5out", this, "pout5");
		addCoupling(f, "p6out", this, "pout6");

		initialize();
		preferredSize = new Dimension(100, 50);
		r1.setPreferredLocation(new Point(13, 18));
		f.setPreferredLocation(new Point(45, 18));

	}

	/**
	 * Automatically generated by the SimView program. Do not edit this manually, as
	 * such changes will get overwritten.
	 */
	public void layoutForSimView() {
		preferredSize = new Dimension(831, 768);
		((ViewableComponent) withName("followers")).setPreferredLocation(new Point(10, 212));
		((ViewableComponent) withName("Robot1")).setPreferredLocation(new Point(11, 32));
	}
}
