package refDemo.RobotFormation;

import java.awt.Dimension;
import java.awt.Point;

import GenCol.doubleEnt;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class Robots1 extends ViewableDigraph {

	public Robots1() {
		super("Robots");

		addInport("vin");
		addInport("L");
		addInport("T");
		addInport("stop");
		addInport("formation");
		addOutport("pout1");
		addOutport("pout2");
		addOutport("pout3");
		addOutport("pout4");
		addOutport("pout5");
		addOutport("pout6");

		addTestInput("vin", new doubleEnt(0), 10);
		addTestInput("vin", new doubleEnt(10), 10);
		addTestInput("vin", new doubleEnt(20), 20);
		addTestInput("vin", new doubleEnt(55), 30);
		addTestInput("pin", new doubleEnt(25), 10);
		addTestInput("pin", new doubleEnt(40), 10);
		addTestInput("pin", new doubleEnt(55), 10);
		addTestInput("pin", new doubleEnt(80), 20);

		ViewableAtomic r1 = new r1controller("Robot1");
		ViewableDigraph f = new followers1();

		add(r1);
		add(f);

		addCoupling(this, "vin", r1, "vin");
		addCoupling(this, "stop", r1, "stop");
		addCoupling(this, "L", r1, "L");
		addCoupling(this, "T", r1, "T");
		addCoupling(this, "formation", r1, "formation");
		addCoupling(this, "stop", f, "stop");
		addCoupling(this, "L", f, "L");
		addCoupling(this, "T", f, "T");
		addCoupling(this, "formation", f, "formation");

		addCoupling(r1, "pout", f, "pin");
		addCoupling(r1, "vout", f, "vin");
		addCoupling(r1, "pout", this, "pout1");
		addCoupling(f, "p2out", this, "pout2");
		addCoupling(f, "p3out", this, "pout3");
		addCoupling(f, "p4out", this, "pout4");
		addCoupling(f, "p5out", this, "pout5");
		addCoupling(f, "p6out", this, "pout6");

		initialize();
		preferredSize = new Dimension(100, 50);
		r1.setPreferredLocation(new Point(13, 18));
		f.setPreferredLocation(new Point(45, 18));

	}

	/**
	 * Automatically generated by the SimView program. Do not edit this manually, as
	 * such changes will get overwritten.
	 */
	public void layoutForSimView() {
		preferredSize = new Dimension(662, 840);
		((ViewableComponent) withName("Robot1")).setPreferredLocation(new Point(138, 85));
		((ViewableComponent) withName("followers")).setPreferredLocation(new Point(-80, 121));
	}
}
