package refDemo.RobotFormation;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class world extends ViewableDigraph {

	public world() {
		super("world");

		// robots
		ViewableDigraph R = new Robots();
		// Experimental frame
		ViewableDigraph E = new Ef();

		add(E);
		add(R);

		initialize();

		addCoupling(E, "velocity", R, "vin");
		addCoupling(E, "T", R, "T");
		addCoupling(E, "L", R, "L");
		addCoupling(E, "command", R, "formation");
		addCoupling(R, "pout6", E, "pin6");
		addCoupling(R, "pout1", E, "pin1");
		isHidden();

		preferredSize = new Dimension(549, 181);
		E.setPreferredLocation(new Point(150, 150));
		R.setPreferredLocation(new Point(150, 30));

	}

	/**
	 * Automatically generated by the SimView program. Do not edit this manually, as
	 * such changes will get overwritten.
	 */
	public void layoutForSimView() {
		preferredSize = new Dimension(2016, 848);
		((ViewableComponent) withName("Robots")).setPreferredLocation(new Point(97, -4));
		((ViewableComponent) withName("Ef")).setPreferredLocation(new Point(-176, 77));
	}
}
