package refDemo.RobotFormation;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class worldoffreespace extends ViewableDigraph {

	public worldoffreespace() {
		super("world");

		//
		ViewableAtomic g = new generator("Generator", 100, "FreeSpaceInput.txt");
		ViewableAtomic ef = new displaydataproc();
		ViewableDigraph r = new Robots1();
		ViewableDigraph d = new display();

//
		add(g);
		add(ef);
		add(r);
		add(d);

		initialize();

		addCoupling(ef, "velocity", r, "vin");
		addCoupling(ef, "T", r, "T");
		addCoupling(ef, "L", r, "L");
		addCoupling(ef, "command", r, "formation");
		addCoupling(ef, "stop", r, "stop");
		addCoupling(r, "pout1", d, "p1in");
		addCoupling(r, "pout2", d, "p2in");
		addCoupling(r, "pout3", d, "p3in");
		addCoupling(r, "pout4", d, "p4in");
		addCoupling(r, "pout5", d, "p5in");
		addCoupling(r, "pout6", d, "p6in");
		isHidden();

		preferredSize = new Dimension(549, 181);
		ef.setPreferredLocation(new Point(150, 150));
		r.setPreferredLocation(new Point(150, 30));

	}

	/**
	 * Automatically generated by the SimView program. Do not edit this manually, as
	 * such changes will get overwritten.
	 */
	public void layoutForSimView() {
		preferredSize = new Dimension(702, 917);
		((ViewableComponent) withName("display")).setPreferredLocation(new Point(112, 310));
		((ViewableComponent) withName("Robots")).setPreferredLocation(new Point(-8, -146));
		((ViewableComponent) withName("Generator")).setPreferredLocation(new Point(126, 148));
		((ViewableComponent) withName("DataProc")).setPreferredLocation(new Point(353, 50));
	}
}
