package refDemo.RadarProject;
//import quantization.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableComponent;


public class R2Method2Model extends RadarModel{

 public R2Method2Model (){
    this("R2Method2Model", -10, 0, Color.blue, 25);
 }

 public R2Method2Model (String name){
    this(name, -10, 0, Color.blue, 25);
 }

 public R2Method2Model(String name, double x, double y, Color color, double range)
 {
   super(name, new TqDetector(), new R2Method2Analyzer(name+"Anz"), x, y, color, range);
 }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(541, 179);
        ((ViewableComponent)withName("R2M2ModelAAnz")).setPreferredLocation(new Point(131, 29));
        ((ViewableComponent)withName("TqDetector")).setPreferredLocation(new Point(-1, 91));
    }
}
