package refDemo.RadarProject;
//import quantization.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableComponent;


public class R2Method1Model extends RadarModel{

 public R2Method1Model (){
    this("R2Method1Model", -10, 0, Color.blue, 25);
 }

 public R2Method1Model(String name, double x, double y, Color color, double range)
 {
   super(name, new TqDetector(), new R2Method1Analyzer(name+"Anz"), x, y, color, range);
 }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(541, 163);
        ((ViewableComponent)withName("R2M1ModelAAnz")).setPreferredLocation(new Point(133, 30));
        ((ViewableComponent)withName("TqDetector")).setPreferredLocation(new Point(2, 91));
    }
}
