package refDemo.RadarProject;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableComponent;

public class R2Method2TestEF extends RadarEF{

  public R2Method2TestEF(){

    super("R2Method2TestEF",new R2Method2Model("R2M2ModelB", 10.0, 0.0, Color.orange, 25),
          new R2Method2Model("R2M2ModelA", -10.0, 0.0, Color.cyan, 25));

    this.tGen.SetTrack(new trackentity("Test1",-50, 50, 136,1,10, new Color(69,69,69)));
//    this.tGen.SetTrack(new trackentity("Test2",-2, 50, 191,1,10, new Color(69,69,69)));
//    this.tGen.SetTrack(new trackentity("Test3",40, 50, 226,1,10, new Color(69,69,69)));

   R2Plot r2P = new R2Plot();

   add(r2P);
   addCoupling(this.radar1, "DetectOut", r2P,"RadarIn");
   addCoupling(this.radar2, "DetectOut", r2P,"RadarIn");

  }
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(887, 536);
        ((ViewableComponent)withName("R2M2ModelB")).setPreferredLocation(new Point(134, 311));
        ((ViewableComponent)withName("TQ Offset Control 2")).setPreferredLocation(new Point(632, 217));
        ((ViewableComponent)withName("R2M2ModelA")).setPreferredLocation(new Point(143, 30));
        ((ViewableComponent)withName("TrackGenerator")).setPreferredLocation(new Point(27, 251));
        ((ViewableComponent)withName("TQ Offset Control 1")).setPreferredLocation(new Point(630, 283));
    }
}
