package refDemo.RadarProject;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class RadarEF extends ViewableDigraph{

  public TQOffsetControl TqOff1;
  public TQOffsetControl TqOff2;
  public TrackGenerator tGen;
  public RadarModel radar1;
  public RadarModel radar2;

  public RadarEF(String name, RadarModel r1,  RadarModel r2){
    super(name);

    radar1 = r1;
    radar2 = r2;

    add(radar1);

    add(radar2);

    TqOff1 = new TQOffsetControl("TQ Offset Control 1",2);
    add(TqOff1);


    TqOff2 = new TQOffsetControl("TQ Offset Control 2",-1);
    add(TqOff2);

    tGen = new TrackGenerator();
    add(tGen);
    RadarCellGridPlot timeP  = new RadarCellGridPlot("Track",false);

  //  RadarCellGridPlot timeP = new RadarCellGridPlot("Track Plot",50,100);
  //  timeP.setCellGridViewLocation(100,300);
   // timeP.setSpaceSize(100,40);
  //  timeP.setCellSize(5);
  //  timeP.setTimeScale(10);

    add(timeP);


    timeP.PlotRadar(radar1.GetX(), radar1.GetY(), Color.red);
    timeP.PlotRadar(radar2.GetX(), radar2.GetY(), Color.blue);

    addCoupling( tGen, "TrackOut", radar1, "TrackEntity");
    addCoupling(radar1 ,"RadarOut", radar2, "RadarIn");
    addCoupling(radar1 ,"RadarOut", TqOff1, "RadarIn");
    addCoupling(TqOff1, "RadarOut", timeP,"RadarIn");

    addCoupling( tGen, "TrackOut", radar2, "TrackEntity");
    addCoupling(radar2 ,"RadarOut", radar1, "RadarIn");
    addCoupling(radar2 ,"RadarOut", TqOff2, "RadarIn");

    addCoupling(TqOff2, "RadarOut", timeP,"RadarIn");
    addCoupling( tGen, "GroundTruth", timeP, "RadarIn");

  }

  public RadarEF(){
    this("RadarEF",new RadarModel("Radar 1", -10.0, 0.0, Color.orange, 25),
         new RadarModel("Radar 2", 10.0, 0.0, Color.cyan, 25));
  }


    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(918, 536);
        ((ViewableComponent)withName("TQ Offset Control 1")).setPreferredLocation(new Point(657, 209));
        ((ViewableComponent)withName("Radar 1")).setPreferredLocation(new Point(155, 30));
        ((ViewableComponent)withName("TQ Offset Control 2")).setPreferredLocation(new Point(658, 286));
        ((ViewableComponent)withName("Radar 2")).setPreferredLocation(new Point(149, 338));
        ((ViewableComponent)withName("TrackGenerator")).setPreferredLocation(new Point(12, 252));
    }
}
