package refDemo.RadarProject;
//import quantization.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;


public class RadarModel extends ViewableDigraph{

protected double m_X;
 protected double m_Y;

public RadarModel (){
    this("RadarModel", new TqDetector(), new R2Analyzer(), 0,0, Color.black, 25);
}

public RadarModel(String name, double x, double y, Color color, double range){
    this(name, new TqDetector(), new R2Analyzer(), x, y, color, range);
}

public RadarModel (String name, TqDetector tqD, R2Analyzer r2A, double x, double y, Color color, double range){

    super(name);

    m_X = x;
    m_Y  = y;
    tqD.SetXYColorRange(x,y,color,range);
    add(tqD);
    add(r2A);


    addInport("TrackEntity");
    addInport("RadarIn");

    addOutport("RadarOut");
    addOutport("DetectOut");

    addTestInput("TrackEntity",new trackentity("T1",7,2,3,4,10,new Color(255, 0, 0)));
    addTestInput("TrackEntity",new trackentity("T1-2",6,3,3,4,10,new Color(255, 0, 0)));
    addTestInput("TrackEntity",new trackentity("T1-3",5,2,3,4,10,new Color(255, 0, 0)));
    addTestInput("TrackEntity",new trackentity("T1-4",4,2,3,4,10,new Color(255, 0, 0)));
    addTestInput("TrackEntity",new trackentity("T1-5",3,2,3,4,10,new Color(255, 0, 0)));
    addTestInput("TrackEntity",new trackentity("T1-6",2,2,3,4,10,new Color(255, 0, 0)));

    addTestInput("TrackEntity",new trackentity("T2-1",5,6,3,4,10,new Color(0, 255, 0)));
    addTestInput("TrackEntity",new trackentity("T2-2",4,6,3,4,10,new Color(0, 255, 0)));
    addTestInput("TrackEntity",new trackentity("T2-3",3,6,3,4,10,new Color(0, 255, 0)));
    addTestInput("TrackEntity",new trackentity("T2-4",2,6,3,4,10,new Color(0, 255, 0)));
    addTestInput("TrackEntity",new trackentity("T2-5",1,6,3,4,10,new Color(0, 255, 0)));
    addTestInput("TrackEntity",new trackentity("T2-6",0,6,3,4,10,new Color(0, 255, 0)));
    addTestInput("TrackEntity",new trackentity("T2-0",-1,6,3,4,10,new Color(0, 255, 0)));

    addCoupling(this,"TrackEntity", tqD,"TrackEntity");

    addCoupling(this,"RadarIn", r2A, "ExtRadarIn");
    addCoupling(tqD,"RadarOut", r2A, "MyRadarIn");

    addCoupling(r2A, "RadarOut", this,"RadarOut");
    addCoupling(tqD, "RadarOut", this,"DetectOut");

}

  public double GetX()
    {

      return m_X;
    }

    public double GetY()
      {

        return m_Y;
      }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(541, 179);
        ((ViewableComponent)withName("TqDetector")).setPreferredLocation(new Point(-77, 60));
        ((ViewableComponent)withName("R2Analyzer")).setPreferredLocation(new Point(129, 27));
    }
}
