package refDemo.NetShortPath;

//native Java library
import java.awt.Dimension;
import java.awt.Point;

import GenCol.doubleEnt;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class networkNode extends ViewableDigraph {

  public networkNode () {
      this("netNode", 1, 1.0);
    }

  public networkNode (String n, int ip, double procTime) {
    super (n);

    ViewableAtomic p = new packetProcessor ("p", ip, procTime);
    ViewableAtomic e = new routeEngine ("e", 0.2, ip);

    add(p);
    add(e);

    addInport ("R");
    addOutport ("T");

    addCoupling (this, "R", p, "in");
    addCoupling (p, "out", this, "T");

    addCoupling (p, "route", e, "in");
    addCoupling (e, "out", p, "proc");

    addRealTestInput ("send", 1);
    addRealTestInput ("send", 2);
    addRealTestInput ("send", 4);
    addRealTestInput ("send", 8);
    addRealTestInput ("send", 16);
    addRealTestInput ("send", 32);
    addRealTestInput ("send", 64);
    addRealTestInput ("send", 128);

    initialize ();
    showState ();

    preferredSize = new Dimension (2000, 1000);
    p.setPreferredLocation (new Point(13, 18));
    e.setPreferredLocation (new Point(500, 18));
  }

  public void addRealTestInput(String port, double value) {
    addTestInput(port, new doubleEnt(value), 0);
  }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(307, 168);
        ((ViewableComponent)withName("e")).setPreferredLocation(new Point(33, 98));
        ((ViewableComponent)withName("p")).setPreferredLocation(new Point(13, 22));
    }
}
