package refDemo.NetShortPath;

//native Java library
import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class wideAreaNetwork_2 extends ViewableDigraph {

  public wideAreaNetwork_2 () {
    super ("wideAreaNetwork");

    ViewableDigraph n1 = new networkNode ("n1", 1, 1.0);
    ViewableDigraph n2 = new networkNode ("n2", 2, 1.0);
    ViewableDigraph n3 = new networkNode ("n3", 4, 1.0);
    ViewableDigraph n4 = new networkNode ("n4", 8, 1.0);
    ViewableDigraph n5 = new networkNode ("n5", 16, 1.0);
    ViewableDigraph n6 = new networkNode ("n6", 32, 1.0);
    ViewableDigraph n7 = new networkNode ("n7", 64, 1.0);
    ViewableDigraph n8 = new networkNode ("n8", 128, 1.0);

    ViewableAtomic link_1_2 = new link ("l_1_2", 2);
    ViewableAtomic link_2_1 = new link ("l_2_1", 2);
    ViewableAtomic link_2_3 = new link ("l_2_3", 2);
    ViewableAtomic link_3_2 = new link ("l_3_2", 2);
    ViewableAtomic link_3_4 = new link ("l_3_4", 2);
    ViewableAtomic link_4_3 = new link ("l_4_3", 2);
    ViewableAtomic link_4_6 = new link ("l_4_6", 2);
    ViewableAtomic link_6_4 = new link ("l_6_4", 2);
    ViewableAtomic link_1_5 = new link ("l_1_5", 20);
    ViewableAtomic link_5_1 = new link ("l_5_1", 20);
    ViewableAtomic link_5_6 = new link ("l_5_6", 1);
    ViewableAtomic link_6_5 = new link ("l_6_5", 1);
    ViewableAtomic link_1_7 = new link ("l_1_7", 5);
    ViewableAtomic link_7_1 = new link ("l_7_1", 5);
    ViewableAtomic link_7_8 = new link ("l_7_8", 3);
    ViewableAtomic link_8_7 = new link ("l_8_7", 3);
    ViewableAtomic link_8_6 = new link ("l_8_6", 2);
    ViewableAtomic link_6_8 = new link ("l_6_8", 2);

    add(n1);
    add(n2);
    add(n3);
    add(n4);
    add(n5);
    add(n6);
    add(n7);
    add(n8);

    add(link_2_1);
    add(link_1_2);
    add(link_2_3);
    add(link_3_2);
    add(link_3_4);
    add(link_4_3);
    add(link_1_5);
    add(link_5_1);
    add(link_5_6);
    add(link_6_5);
    add(link_4_6);
    add(link_6_4);
    add(link_1_7);
    add(link_7_1);
    add(link_7_8);
    add(link_8_7);
    add(link_8_6);
    add(link_6_8);

    addCoupling (n2, "T", link_2_1, "r");
    addCoupling (link_2_1, "t", n1, "R");
    addCoupling (n1, "T", link_1_2, "r");
    addCoupling (link_1_2, "t", n2, "R");

    addCoupling (n1, "T", link_1_5, "r");
    addCoupling (link_1_5, "t", n5, "R");
    addCoupling (n5, "T", link_5_1, "r");
    addCoupling (link_5_1, "t", n1, "R");

    addCoupling (n2, "T", link_2_3, "r");
    addCoupling (link_2_3, "t", n3, "R");
    addCoupling (n3, "T", link_3_2, "r");
    addCoupling (link_3_2, "t", n2, "R");

    addCoupling (n3, "T", link_3_4, "r");
    addCoupling (link_3_4, "t", n4, "R");
    addCoupling (n4, "T", link_4_3, "r");
    addCoupling (link_4_3, "t", n3, "R");

    addCoupling (n4, "T", link_4_6, "r");
    addCoupling (link_4_6, "t", n6, "R");
    addCoupling (n6, "T", link_6_4, "r");
    addCoupling (link_6_4, "t", n4, "R");

    addCoupling (n5, "T", link_5_6, "r");
    addCoupling (link_5_6, "t", n6, "R");
    addCoupling (n6, "T", link_6_5, "r");
    addCoupling (link_6_5, "t", n5, "R");

    addCoupling (n1, "T", link_1_7, "r");
    addCoupling (link_1_7, "t", n7, "R");
    addCoupling (n7, "T", link_7_1, "r");
    addCoupling (link_7_1, "t", n1, "R");

    addCoupling (n7, "T", link_7_8, "r");
    addCoupling (link_7_8, "t", n8, "R");
    addCoupling (n8, "T", link_8_7, "r");
    addCoupling (link_8_7, "t", n7, "R");

    addCoupling (n8, "T", link_8_6, "r");
    addCoupling (link_8_6, "t", n6, "R");
    addCoupling (n6, "T", link_6_8, "r");
    addCoupling (link_6_8, "t", n8, "R");

    initialize ();
    showState ();
  }
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1213, 764);
        ((ViewableComponent)withName("n8")).setPreferredLocation(new Point(438, 169));
        ((ViewableComponent)withName("l_6_8")).setPreferredLocation(new Point(769, 260));
        ((ViewableComponent)withName("l_5_1")).setPreferredLocation(new Point(981, 586));
        ((ViewableComponent)withName("l_6_5")).setPreferredLocation(new Point(947, 198));
        ((ViewableComponent)withName("l_3_2")).setPreferredLocation(new Point(182, 453));
        ((ViewableComponent)withName("l_3_4")).setPreferredLocation(new Point(-3, 186));
        ((ViewableComponent)withName("l_7_8")).setPreferredLocation(new Point(371, 323));
        ((ViewableComponent)withName("n6")).setPreferredLocation(new Point(678, 6));
        ((ViewableComponent)withName("l_8_7")).setPreferredLocation(new Point(526, 326));
        ((ViewableComponent)withName("l_1_5")).setPreferredLocation(new Point(918, 522));
        ((ViewableComponent)withName("n7")).setPreferredLocation(new Point(426, 394));
        ((ViewableComponent)withName("l_5_6")).setPreferredLocation(new Point(1034, 279));
        ((ViewableComponent)withName("l_6_4")).setPreferredLocation(new Point(416, 83));
        ((ViewableComponent)withName("l_2_1")).setPreferredLocation(new Point(246, 660));
        ((ViewableComponent)withName("n4")).setPreferredLocation(new Point(33, 26));
        ((ViewableComponent)withName("l_8_6")).setPreferredLocation(new Point(769, 193));
        ((ViewableComponent)withName("n2")).setPreferredLocation(new Point(114, 514));
        ((ViewableComponent)withName("l_1_7")).setPreferredLocation(new Point(557, 543));
        ((ViewableComponent)withName("l_7_1")).setPreferredLocation(new Point(409, 542));
        ((ViewableComponent)withName("l_4_3")).setPreferredLocation(new Point(159, 189));
        ((ViewableComponent)withName("l_2_3")).setPreferredLocation(new Point(29, 452));
        ((ViewableComponent)withName("l_1_2")).setPreferredLocation(new Point(91, 660));
        ((ViewableComponent)withName("n5")).setPreferredLocation(new Point(824, 352));
        ((ViewableComponent)withName("n1")).setPreferredLocation(new Point(473, 609));
        ((ViewableComponent)withName("n3")).setPreferredLocation(new Point(65, 262));
        ((ViewableComponent)withName("l_4_6")).setPreferredLocation(new Point(417, 22));
    }
}
