package refDemo.NetShortPath;

//native Java library
import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class wideAreaNetwork extends ViewableDigraph {

  public wideAreaNetwork () {
    super ("wideAreaNetwork");

    ViewableDigraph n1 = new networkNode ("n1", 1, 1.0);
    ViewableDigraph n2 = new networkNode ("n2", 2, 1.0);
    ViewableDigraph n3 = new networkNode ("n3", 4, 1.0);

    ViewableAtomic link_1_2 = new link ("l_1_2", 1);
    ViewableAtomic link_2_1 = new link ("l_2_1", 1);
    ViewableAtomic link_1_3 = new link ("l_1_3", 2);
    ViewableAtomic link_3_1 = new link ("l_3_1", 2);
    ViewableAtomic link_2_3 = new link ("l_2_3", 4);
    ViewableAtomic link_3_2 = new link ("l_3_2", 4);

    add(n1);
    add(n2);
    add(n3);
    add(link_2_1);
    add(link_1_2);
    add(link_1_3);
    add(link_3_1);
    add(link_2_3);
    add(link_3_2);

    addCoupling (n2, "T", link_2_1, "r");
    addCoupling (link_2_1, "t", n1, "R");
    addCoupling (n1, "T", link_1_2, "r");
    addCoupling (link_1_2, "t", n2, "R");

    addCoupling (n1, "T", link_1_3, "r");
    addCoupling (link_1_3, "t", n3, "R");
    addCoupling (n3, "T", link_3_1, "r");
    addCoupling (link_3_1, "t", n1, "R");

    addCoupling (n2, "T", link_2_3, "r");
    addCoupling (link_2_3, "t", n3, "R");
    addCoupling (n3, "T", link_3_2, "r");
    addCoupling (link_3_2, "t", n2, "R");

    n1.setBlackBox (true);
    n2.setBlackBox (true);
    n3.setBlackBox (true);

    initialize ();
    showState ();
  }
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1040, 717);
        ((ViewableComponent)withName("l_2_1")).setPreferredLocation(new Point(567, 329));
        ((ViewableComponent)withName("n3")).setPreferredLocation(new Point(50, 50));
        ((ViewableComponent)withName("l_3_1")).setPreferredLocation(new Point(402, 100));
        ((ViewableComponent)withName("l_2_3")).setPreferredLocation(new Point(62, 334));
        ((ViewableComponent)withName("l_1_3")).setPreferredLocation(new Point(402, 26));
        ((ViewableComponent)withName("l_1_2")).setPreferredLocation(new Point(719, 331));
        ((ViewableComponent)withName("l_3_2")).setPreferredLocation(new Point(206, 333));
        ((ViewableComponent)withName("n1")).setPreferredLocation(new Point(677, 29));
        ((ViewableComponent)withName("n2")).setPreferredLocation(new Point(359, 442));
    }
}
