package refDemo.NetShortPath;

//native Java library
import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class wideAreaNetwork_1 extends ViewableDigraph {

  public wideAreaNetwork_1 () {
    super ("wideAreaNetwork");

    ViewableDigraph n1 = new networkNode ("n1", 1, 1.0);
    ViewableDigraph n2 = new networkNode ("n2", 2, 1.0);
    ViewableDigraph n3 = new networkNode ("n3", 4, 1.0);
    ViewableDigraph n4 = new networkNode ("n4", 8, 1.0);
    ViewableDigraph n5 = new networkNode ("n5", 16, 1.0);
    ViewableDigraph n6 = new networkNode ("n6", 32, 1.0);


    ViewableAtomic link_1_2 = new link ("l_1_2", 2);
    ViewableAtomic link_2_1 = new link ("l_2_1", 2);
    ViewableAtomic link_2_3 = new link ("l_2_3", 2);
    ViewableAtomic link_3_2 = new link ("l_3_2", 2);
    ViewableAtomic link_3_4 = new link ("l_3_4", 2);
    ViewableAtomic link_4_3 = new link ("l_4_3", 2);
    ViewableAtomic link_4_6 = new link ("l_4_6", 2);
    ViewableAtomic link_6_4 = new link ("l_6_4", 2);
    ViewableAtomic link_1_5 = new link ("l_1_5", 20);
    ViewableAtomic link_5_1 = new link ("l_5_1", 20);
    ViewableAtomic link_5_6 = new link ("l_5_6", 1);
    ViewableAtomic link_6_5 = new link ("l_6_5", 1);

    add(n1);
    add(n2);
    add(n3);
    add(n4);
    add(n5);
    add(n6);

    add(link_2_1);
    add(link_1_2);
    add(link_2_3);
    add(link_3_2);
    add(link_3_4);
    add(link_4_3);
    add(link_1_5);
    add(link_5_1);
    add(link_5_6);
    add(link_6_5);
    add(link_4_6);
    add(link_6_4);

    addCoupling (n2, "T", link_2_1, "r");
    addCoupling (link_2_1, "t", n1, "R");
    addCoupling (n1, "T", link_1_2, "r");
    addCoupling (link_1_2, "t", n2, "R");

    addCoupling (n1, "T", link_1_5, "r");
    addCoupling (link_1_5, "t", n5, "R");
    addCoupling (n5, "T", link_5_1, "r");
    addCoupling (link_5_1, "t", n1, "R");

    addCoupling (n2, "T", link_2_3, "r");
    addCoupling (link_2_3, "t", n3, "R");
    addCoupling (n3, "T", link_3_2, "r");
    addCoupling (link_3_2, "t", n2, "R");

    addCoupling (n3, "T", link_3_4, "r");
    addCoupling (link_3_4, "t", n4, "R");
    addCoupling (n4, "T", link_4_3, "r");
    addCoupling (link_4_3, "t", n3, "R");

    addCoupling (n4, "T", link_4_6, "r");
    addCoupling (link_4_6, "t", n6, "R");
    addCoupling (n6, "T", link_6_4, "r");
    addCoupling (link_6_4, "t", n4, "R");

    addCoupling (n5, "T", link_5_6, "r");
    addCoupling (link_5_6, "t", n6, "R");
    addCoupling (n6, "T", link_6_5, "r");
    addCoupling (link_6_5, "t", n5, "R");

    initialize ();
    showState ();
  }
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1373, 868);
        ((ViewableComponent)withName("l_6_5")).setPreferredLocation(new Point(1048, 248));
        ((ViewableComponent)withName("l_5_6")).setPreferredLocation(new Point(1200, 248));
        ((ViewableComponent)withName("n1")).setPreferredLocation(new Point(580, 668));
        ((ViewableComponent)withName("n5")).setPreferredLocation(new Point(1062, 360));
        ((ViewableComponent)withName("n4")).setPreferredLocation(new Point(30, 22));
        ((ViewableComponent)withName("l_3_2")).setPreferredLocation(new Point(276, 427));
        ((ViewableComponent)withName("n2")).setPreferredLocation(new Point(468, 439));
        ((ViewableComponent)withName("l_3_4")).setPreferredLocation(new Point(-3, 186));
        ((ViewableComponent)withName("l_5_1")).setPreferredLocation(new Point(963, 708));
        ((ViewableComponent)withName("l_6_4")).setPreferredLocation(new Point(420, 143));
        ((ViewableComponent)withName("l_2_1")).setPreferredLocation(new Point(283, 780));
        ((ViewableComponent)withName("l_4_3")).setPreferredLocation(new Point(159, 189));
        ((ViewableComponent)withName("l_4_6")).setPreferredLocation(new Point(417, 47));
        ((ViewableComponent)withName("n3")).setPreferredLocation(new Point(65, 262));
        ((ViewableComponent)withName("l_1_5")).setPreferredLocation(new Point(959, 626));
        ((ViewableComponent)withName("n6")).setPreferredLocation(new Point(720, 13));
        ((ViewableComponent)withName("l_1_2")).setPreferredLocation(new Point(70, 686));
        ((ViewableComponent)withName("l_2_3")).setPreferredLocation(new Point(29, 452));
    }
}
