/*     
 *    
 *  Author     : ACIMS(Arizona Centre for Integrative Modeling & Simulation)
 *  Version    : DEVSJAVA 2.7 
 *  Date       : 08-15-02 
 */
package ComponetAntiAirFleet;

import java.awt.Dimension;
import java.awt.Point;

import ComponentMod.ef2;

import ComponetAntiAirFleet.SimpleTestAntiAirFleet2;
import GenCol.entity;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class efp2 extends ViewableDigraph {

	public efp2() {
		super("efp2");
		// ViewableDigraph sp = new procSpec("proc",25);
		// ViewableAtomic sp = new proc("proc",25);
		// ViewableDigraph sp = new DandC3("d",29);
		// ViewableDigraph sp = new divideAndConquer("d",29,3);
		// ViewableDigraph sp = new pipe3("p",30);
		// ViewableDigraph sp = new pipeLine("p",30,3);
		// ViewableDigraph sp = new Multi3("m",3);
		ViewableDigraph sp = new SimpleTestAntiAirFleet2("m");

		ViewableDigraph expf = new ef2("ExpFrame", 30, 10);

		add(expf);

		add(sp);

		addTestInput("start", new entity());

		addCoupling(this, "start", expf, "start");
		addCoupling(this, "stop", expf, "stop");

		addCoupling(expf, "out", sp, "in");
		addCoupling(sp, "out", expf, "in");

		initialize();

	/*	preferredSize = new Dimension(900, 600);
		expf.setPreferredLocation(new Point(5, 5));
		sp.setPreferredLocation(new Point(150, 150));*/
	}

	/**
	 * Automatically generated by the SimView program. Do not edit this manually, as
	 * such changes will get overwritten.
	 */
	public void layoutForSimView() {
		preferredSize = new Dimension(1500, 700);
		((ViewableComponent) withName("ExpFrame")).setPreferredLocation(new Point(5, 5));
		((ViewableComponent) withName("m")).setPreferredLocation(new Point(450, 180));
	}
}
