/*
*			Copyright Author
* (USE & RESTRICTIONS - Please read COPYRIGHT file)

* Version		: XX.XX
* Date		: 18-10-29 ����2:01
*/

// Default Package
package ComponetAntiAirFleet;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;

public class RedMissile_1_1 extends view.modeling.ViewableDigraph {

	// Add Default Constructor
	public RedMissile_1_1() {
		this("RedMissile_1_1");
	}

	// Add Parameterized Constructor
	public RedMissile_1_1(String name) {
		super(name);

// Structure information start
		// Add input port names
		addInport("in");//接收实验帧的输入：missile1
		addInport("in2");
		addInport("in3");
		addInport("in4");
		addInport("in5");

		// Add output port names
		addOutport("out");
		addOutport("out2");
		addOutport("hit_out");

//add test input ports:

		// Initialize sub-components
		ViewableAtomic Sensor_1_0 = new Sensor_0_0("Sensor_1_0");
		ViewableAtomic RedController_1_0 = new RedController_0_0("RedController_1_0");
		ViewableAtomic Advance_1_0 = new Advance_0_0("Advance_1_0");

		// Add sub-components
		add(Sensor_1_0);
		add(RedController_1_0);
		add(Advance_1_0);

		// Add Couplings
		addCoupling(this, "in", Sensor_1_0, "in");
		
		addCoupling(Advance_1_0, "missileLoc_out", RedController_1_0, "missileLoc_in");
		addCoupling(RedController_1_0, "advance_out", Advance_1_0, "advance_in");
		addCoupling(this, "in5", Sensor_1_0, "in5");
		addCoupling(this, "in4", Sensor_1_0, "in4");
		addCoupling(RedController_1_0, "redDestroyed_out",this, "out2");
		addCoupling(RedController_1_0, "hit_out",this, "hit_out");
		addCoupling(Advance_1_0, "missileLoc_out",this, "out");
		addCoupling(this, "in3", Sensor_1_0, "in3");
		addCoupling(this, "in2", Sensor_1_0, "in2");
		addCoupling(Sensor_1_0, "out2", RedController_1_0, "missileExplode_in");
		addCoupling(Sensor_1_0, "out", RedController_1_0, "shipLoc_in");
		
		addCoupling(RedController_1_0, "redDestroyed_out", Sensor_1_0, "in2");

// Structure information end
		initialize();
	}
	
	/**
	 * Automatically generated by the SimView program. Do not edit this manually, as
	 * such changes will get overwritten.
	 */
	public void layoutForSimView() {
		preferredSize = new Dimension(550, 350);
		((ViewableComponent) withName("Sensor_1_0")).setPreferredLocation(new Point(15, 15));
		((ViewableComponent) withName("RedController_1_0")).setPreferredLocation(new Point(90, 250));
		((ViewableComponent) withName("Advance_1_0")).setPreferredLocation(new Point(220, 50));
	}

}
